name: panecho
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy>=1.23
  - pandas>=1.5
  - scikit-learn>=1.1
  - matplotlib>=3.6
  - tqdm
  - pip:
      - torch>=2.1.0
      - torchvision>=0.16.0
      - timm==0.9.10
      - safetensors
      - huggingface_hub
      - opencv-python
      - Pillow>=9.0
      - imageio
